### ISSUE TITLE
switch to golangci-lint from gometalinter

### ISSUE THREAD

**Issue by joelrebel** [bmc-toolbox/bmcbutler#13]
The gometalinter project is archived https://github.com/alecthomas/gometalinter/issues/590
bmcbutler travis builds currently fail because of this,
https://travis-ci.org/bmc-toolbox/bmcbutler/jobs/514147757#L468

**Comment by alecthomas** [comment]
The issue you're seeing is unrelated to archiving. The error you're seeing is caused by using `go get` with modules enabled, which gometalinter does not support. Use a binary release.

**Comment by joelrebel** [comment]
@alecthomas thanks for pointing this out, and your work on gometalinter!
